export default {
  'general.filter': 'filter',
  'general.filter.actor': 'Actor',
  'general.filter.availability': 'Availability',
  'general.filter.availability.available': 'available',
  'general.filter.availability.unavailable': 'unavailable',
  'general.filter.clearfilter': 'Clear Filter',
  'general.filter.contentrating': 'Content Rating',
  'general.filter.director': 'Director',
  'general.filter.year': 'Year',
  'general.navigation.guide': 'Guide',
  'general.navigation.home': 'Home',
  'general.navigation.mylibrary': 'My library',
  'general.navigation.ondemand': 'On demand ',
  'general.navigation.settings': 'Settings',
  'general.search.cutv': 'CuTV',
  'general.search.noresults': 'No results',
  'general.search.ondemand': 'On Demand',
  'general.search.searchcontent': 'Search',
  'general.search.searchcontent.search.action': 'Search button',
  'general.search.tv': 'TV',
  'general.seeall': 'see all',
  'general.sort': 'sort',
  'general.sort.az': 'A-Z',
  'general.sort.channel': 'channel',
  'general.sort.clearsort': 'Clear Sort',
  'general.sort.date': 'date',
  'general.sort.dateadded': 'Date added',
  'general.sort.duration': 'Duration',
  'general.sort.event': 'event',
  'general.sort.mostlistened': 'Most listened',
  'general.sort.mostwatched': 'most watched',
  'general.sort.rating': 'Rating',
  'general.sort.recommended': 'Recommended',
  'general.sort.releasedate': 'Release date',
  'general.sort.time': 'Time',
  'guide.alltv': 'All TV',
  'guide.alltv.favorites.choosefilter': 'Filter',
  'guide.alltv.favorites.customlist.delete': 'delete custom list',
  'guide.alltv.favorites.edit': 'Edit',
  'guide.alltv.favorites.filter.searchchannel': 'Search channel',
  'guide.alltv.favorites.ok': 'Ok',
  'guide.alltv.favorites.radio': 'Radio',
  'guide.alltv.favorites.tv': 'TV',
  'guide.calendar.date': 'Date',
  'guide.calendar.date.dayname': 'Days',
  'guide.calendar.datetimeslot': 'Date & Timeslot',
  'guide.calendar.datetimeslot.ok': 'Ok',
  'guide.calendar.dayname': 'Today (day name)',
  'guide.calendar.timeslot.afternoon': 'Afternoon',
  'guide.calendar.timeslot.evening': 'Evening',
  'guide.calendar.timeslot.latenight': 'Late Night',
  'guide.calendar.timeslot.morning': 'Morning',
  'guide.eventplaying.back': 'Back',
  'guide.eventplaying.connecttodevice': 'Connect to device',
  'guide.eventplaying.playevent': 'Play event',
  'guide.eventplaying.playevent.playondevice': 'play on device',
  'guide.eventplaying.playevent.playondevice.description': 'Description',
  'guide.eventplaying.playevent.playondevice.disconnect': 'Disconnect',
  'guide.eventplaying.playevent.playondevice.title': 'Title ',
  'guide.live': 'Live',
  'guide.nowplaying': 'now',
  'guide.nowtv': 'Now TV',
  'guide.nowtv.before': 'Before',
  'guide.nowtv.event.details.cast': 'cast',
  'guide.nowtv.event.details.director': 'director',
  'guide.nowtv.event.details.download': 'Download',
  'guide.nowtv.event.details.favorites': 'Favorites',
  'guide.nowtv.event.details.language': 'language',
  'guide.nowtv.event.details.noinfo': 'No Info',
  'guide.nowtv.event.details.record': 'record',
  'guide.nowtv.next': 'Next',
  'guide.nowtv.now': 'Now ',
  'guide.radio.allradio': 'All radio',
  'home.apps': 'Apps',
  'home.notifications.message.delete': 'Delete',
  'home.notifications.newmessages': 'New messages',
  'home.notifications.nomessages': 'No messages',
  'home.nowontv': 'Now on TV',
  'home.ondemand': 'On demand ',
  'home.radio': 'Radio Stations',
  'home.view.foryou': 'For you',
  'home.view.viewall': 'View all',
  'login.createpincode.done': 'done',
  'login.createpincode.enterpincode': 'enter pincode',
  'login.createpincode.reenterpincode': 're-enter pincode',
  'login.createpincode.skip': 'skip this',
  'login.createpincode.userpincode': 'User pincode',
  'login.createprofile.addphoto': 'add photo',
  'login.createprofile.dateofbirth': 'date of birth',
  'login.createprofile.done': 'done',
  'login.createprofile.enablepincode': 'enable pincode',
  'login.createprofile.error': 'text error creating profile',
  'login.createprofile.genderselection': 'gender',
  'login.createprofile.genderselection.female': 'f',
  'login.createprofile.genderselection.male': 'm ',
  'login.createprofile.infotext': 'text info (user manual)',
  'login.createprofile.name': 'name',
  'login.createprofile.password': 'password',
  'login.createprofile.save': 'save',
  'login.createprofile.signin': 'Sign in',
  'login.createprofile.username': 'username ',
  'login.createprofile.userprofile': 'User profile',
  'login.editprofile.changephoto': 'Change photo',
  'login.editprofile.changepin.back': 'Back',
  'login.editprofile.changepin.disablepin': 'Disable ',
  'login.editprofile.changepin.done': 'Done',
  'login.editprofile.changepin.enternew': 'Enter new pincode',
  'login.editprofile.changepin.reenternew': 're-enter new pincode',
  'login.editprofile.changepin.userpincode': 'User Pincode',
  'login.editprofile.changepincode': 'Change pincode',
  'login.editprofile.delete': 'Delete',
  'login.editprofile.done': 'Done',
  'login.editprofile.pin.action.unlock': 'Unlock',
  'login.editprofile.pin.profilelogin.description': 'Enter pincode to unlock',
  'login.editprofile.pin.profilelogin.title': 'Profile login',
  'login.editprofile.save': 'Save',
  'login.introductionscreen.next': 'Next',
  'login.introductionscreen.signin': 'Sign in',
  'login.language.selectlanguage': 'Select language',
  'login.loading': 'Loading',
  'login.whoswatching': `Who's watching`,
  'login.whoswatching.addprofile': 'Add profile',
  'login.whoswatching.editprofile': 'Edit',
  'login.whoswatching.editprofile.title': 'Edit profile',
  'login.whoswatching.family': 'Continue as Family',
  'message.guide.action.contact': 'Contact',
  'message.guide.action.unlock': 'Unlock',
  'message.guide.action.view': 'View',
  'message.guide.description.enterpincode': 'Enter pincode to unlock',
  'message.guide.description.problem.channelunavailable': 'Selected channel is not available in your country. For more information, please call our contact center.',
  'message.guide.description.problem.copyrightissue': 'Content is blocked due to copyright issue. For more information, please call our contact center.',
  'message.guide.description.problem.notsubsribed.channel': 'You are not subscribed to this channel. For more information, please call our contact center.',
  'message.guide.description.problem.notsubsribed.service': 'You are not subscribed to our service. For more information, please call our contact center.',
  'message.guide.description.problem.signalerror': 'An error receiving the signal has occurred. Please call our contact center.',
  'message.guide.description.problem.subscriptionexpired': 'Your subscription has expired. To renew your subscription, please call our contact center.',
  'message.guide.title.info': 'Information',
  'message.guide.title.lockedchannel': 'Locked channel',
  'message.guide.title.reminders': 'Reminders',
  'mylibrary.download': 'Download',
  'mylibrary.download.disksize': 'Disk size',
  'mylibrary.download.downloadedondemand': 'Downloaded On demand',
  'mylibrary.download.downloadedtvcontent': 'Downloaded TV content',
  'mylibrary.dvr': 'DVR',
  'mylibrary.dvr.completedrecordings': 'Completed recordings',
  'mylibrary.dvr.memorysize': 'Memory size',
  'mylibrary.dvr.ongoingrecordings': 'Ongoing recordings',
  'mylibrary.dvr.scheduledrecordings': 'Scheduled recordings',
  'mylibrary.favorites': 'favorites',
  'mylibrary.favorites.ondemand': 'On demand ',
  'mylibrary.favorites.tvevents': 'TV events',
  'mylibrary.less': 'Less',
  'mylibrary.more': 'More',
  'mylibrary.nodownload.description': 'No download description',
  'mylibrary.nodownload.title': 'No download',
  'mylibrary.nodvr.description': 'no dvr description',
  'mylibrary.nodvr.title': 'no dvr',
  'mylibrary.nofavorites.description': 'No favorites description',
  'mylibrary.nofavorites.title': 'No favorites',
  'mylibrary.nopurchase.description': 'No purchase description',
  'mylibrary.nopurchase.title': 'No purchase',
  'mylibrary.noreminder.description': 'No reminder description',
  'mylibrary.noreminder.title': 'No reminder',
  'mylibrary.purchase': 'purchase',
  'mylibrary.purchase.available': 'available',
  'mylibrary.purchase.expired': 'expired',
  'mylibrary.reminder': 'Reminder',
  'ondemand.categories': 'CATEGORIES',
  'ondemand.continuewatching.seeall.catalogues': 'catalogues',
  'ondemand.continuewatching.seeall.catalogues.clearselction': 'clear selection',
  'ondemand.detailedscreen.availablefor.duration': 'Available for rental until dd.mm.yyyy',
  'ondemand.detailedscreen.availablein.duration': 'Available in next 48h',
  'ondemand.detailedscreen.cast': 'cast',
  'ondemand.detailedscreen.castandcrew': 'cast and crew',
  'ondemand.detailedscreen.director': 'director',
  'ondemand.detailedscreen.favorites': 'favorites',
  'ondemand.detailedscreen.hd': 'hd',
  'ondemand.detailedscreen.language': 'language',
  'ondemand.detailedscreen.morelikethis': 'More like this',
  'ondemand.detailedscreen.notsubscribed': 'not subscribed',
  'ondemand.detailedscreen.notsubscribed.information.action.ok': 'ok',
  'ondemand.detailedscreen.notsubscribed.information.description': 'You are not subscribed to this catalogue. Please call our contact center or visit selfcare portal.',
  'ondemand.detailedscreen.notsubscribed.information.title': 'information',
  'ondemand.detailedscreen.price': 'hd price/sd price',
  'ondemand.detailedscreen.price.currency': 'currency',
  'ondemand.detailedscreen.rent': 'rent',
  'ondemand.detailedscreen.rentfor.currency.title': 'Rent for X RSD',
  'ondemand.detailedscreen.rentfor.description': 'Rent for 2 days. Available for rental until dd.mm.yyyy.',
  'ondemand.detailedscreen.rentfor.duration': 'rent for x days',
  'ondemand.detailedscreen.sd': 'sd',
  'ondemand.detailedscreen.seasons': 'seasons',
  'ondemand.detailedscreen.seasons.back': 'back',
  'ondemand.detailedscreen.subscribed': 'subscribed',
  'ondemand.detailedscreen.synopsys': 'Synopsys',
  'ondemand.detailedscreen.synopsys.more': 'More',
  'ondemand.detailedscreen.titles': 'Titles',
  'ondemand.detailedscreen.trailer': 'trailer',
  'ondemand.detailedscreen.transitionalscreen.purchasing.description': 'To purchase this event please visit www.d3go.tv or do it on your stb.',
  'ondemand.detailedscreen.transitionalscreen.purchasing.ok': 'Ok',
  'ondemand.detailedscreen.transitionalscreen.purchasing.title': 'Purchasing',
  'ondemand.detailedscreen.watch': 'watch',
  'ondemand.genre': 'GENRE',
  'ondemand.landingpage.allcatalogues': 'all catalogues',
  'ondemand.landingpage.continuewatching': 'Continue watching',
  'ondemand.landingpage.recentlyaddedkids.title': 'Recently added kids',
  'ondemand.landingpage.recentlyaddedmovies': 'Recently added movies',
  'ondemand.landingpage.recentlyaddedseries': 'Recently added series',
  'ondemand.landingpage.rentandwatch': 'rent and watch',
  'phone.guide.alltv.favorites.newlist.action.save': 'Save',
  'phone.guide.alltv.favorites.newlist.description': 'Name of the list',
  'phone.guide.alltv.favorites.newlist.title': 'New list',
  'settings.about': 'About',
  'settings.about.aboutsection': 'about',
  'settings.about.aboutsection.version': 'version ',
  'settings.account': 'Account',
  'settings.account.accountsection': 'Account ',
  'settings.account.accountsection.description': 'You are currently signed in with this acount ',
  'settings.account.signout': 'sign out',
  'settings.changepin': 'Change pin',
  'settings.changepin.changepinsection': 'Change pin',
  'settings.changepin.changepinsection.confirmnew': 'confirm new pin',
  'settings.changepin.changepinsection.description': 'the master pincode must be a four digit number. A master pincode is necessary in order to view age-rated content ',
  'settings.changepin.changepinsection.newpin': 'new pin',
  'settings.changepin.changepinsection.ok': 'ok',
  'settings.changepin.changepinsection.oldpin': 'old pin',
  'settings.devicemanagement': 'Device management',
  'settings.devicemanagement.description': 'You can change your devices maximum 5 times a month. This shows your remaining requests.',
  'settings.devicemanagement.done': 'done',
  'settings.devicemanagement.refresh': 'Refresh',
  'settings.devicemanagement.registereddeviccessection': 'Registered devices',
  'settings.download': 'DOWNLOAD',
  'settings.download.resolutionsection': 'resolution',
  'settings.download.resolutionsection.high': 'high',
  'settings.download.resolutionsection.low': 'low',
  'settings.download.resolutionsection.medium': 'medium ',
  'settings.download.storagelimitsection': 'Storage limit',
  'settings.download.storagelimitsection.nolimit': 'No limit',
  'settings.download.storagelimitsection.nolimit.availability': 'x gb available',
  'settings.download.storagelimitsection.nolimit.usage': 'x mb in use',
  'settings.dvr': 'DVR',
  'settings.dvr.endsection': 'ends',
  'settings.dvr.endsection.oneventtime': 'on event time',
  'settings.dvr.endsection.timeafter': 'x min after',
  'settings.dvr.startsection': 'Starts',
  'settings.dvr.startsection.oneventtime': 'On event time',
  'settings.dvr.startsection.timebefore': 'x min before',
  'settings.help': 'HELP',
  'settings.help.callcenternumber': 'Call center number',
  'settings.help.website': 'website',
  'settings.language': 'Language',
  'settings.reminder': 'Reminder',
  'settings.reminder.remindersection': 'reminder',
  'settings.reminder.remindersection.onevettime': 'on event time',
  'settings.reminder.remindersection.timebefore': 'X min before',
  'settings.summary': 'Summary',
  'settings.summary.buyerid': 'buyer id',
  'settings.summary.contactnumber': 'contract number',
  'settings.summary.deviceid': 'device id',
  'settings.summary.devicemodel': 'device model',
  'settings.summary.language': 'language',
  'settings.summary.networkstatus': 'network status',
  'settings.summary.subscriptionpackage': 'subscription package',
  'settings.summary.videoquality': 'video quality',
  'settings.videoquality': 'Video quality',
  'settings.videoquality.auto': 'auto',
  'settings.videoquality.bps': 'bps',
  'settings.videoquality.cellular': 'cellular',
  'settings.videoquality.cellular.auto': 'auto ',
  'settings.videoquality.cellular.bps': 'bps',
  'settings.videoquality.wifi': 'wifi',
  'stb.general.navigation.help': 'Help',
  'stb.general.navigation.profilename': 'Profile name',
  'stb.general.sort.description': 'Description',
  'stb.guide.categories': 'Categories',
  'stb.guide.categories.clear categories': 'Clear categories',
  'stb.guide.categories.description': 'Description',
  'stb.guide.nowtv': 'Now TV',
  'stb.guide.nowtv.details.reminder': 'Reminder',
  'stb.guide.nowtv.details.startover': 'Start over',
  'stb.guide.nowtv.details.watch': 'Watch',
  'stb.guide.nowtv.event.details.description': 'Description',
  'stb.guide.nowtv.event.details.seefull': 'See full',
  'stb.guide.nowtv.event.details.starring': 'starring',
  'stb.guide.nowtv.event.details.synopsys': 'Synopsys',
  'stb.guide.radio.next': 'next',
  'stb.guide.radio.youarelistening': 'you are listening',
  'stb.guide.radiostations': 'Radio Stations',
  'stb.guide.radiostations.genre': 'Genre',
  'stb.guide.tvchannels': 'TV Channels',
  'stb.home.apps.topfree.mostpopular.subtitle': 'most popular',
  'stb.home.apps.topfree.title': 'Top free apps',
  'stb.home.notifications.topright': 'Notifications',
  'stb.home.ondemand.videoondemand.mostpopular.subtitle': 'most popular',
  'stb.home.ondemand.videoondemand.title': 'Video on demand',
  'stb.home.title.topright': 'Home title',
  'stb.home.view.general': 'General',
  'stb.loading.error.networkerror': '403 - Network error',
  'stb.loading.error.systemerror': '407 - System error',
  'stb.loading.update.error': '405 - Update error',
  'stb.loading.update.inprogress': 'Update is in progress',
  'stb.login.activation.activationcode': 'Activation code',
  'stb.login.activation.errormessage.action.log': 'Log',
  'stb.login.activation.errormessage.action.retry': 'Retry',
  'stb.login.activation.errormessage.description': 'Description',
  'stb.login.activation.errormessage.title': 'Error message (title)',
  'stb.login.activation.instructions.item1': 'Go to x.com on your computer or mobile device',
  'stb.login.activation.instructions.item2': 'When prompted, enter the activation code below',
  'stb.login.activation.instructions.item3': '',
  'stb.login.activation.updateinfo': 'This screen will automatically update once your device has been linked to your X account',
  'stb.mylibrary.dvr.detailedscreen.delete': 'delete',
  'stb.mylibrary.dvr.disksize': 'disk size',
  'stb.ondemand.detailedscreen.markasunwatched': 'Mark as unwatched',
  'stb.ondemand.detailedscreen.markaswatched': 'Mark as watched',
  'stb.ondemand.detailedscreen.more': 'More',
  'stb.ondemand.detailedscreen.qualityrentedfor': 'SD quality rented for X RSD',
  'stb.ondemand.detailedscreen.rentfor.cancel': 'Cancel',
  'stb.ondemand.detailedscreen.rentquality.button': 'Rent HD/SD',
  'stb.ondemand.detailedscreen.starring': 'Starring',
  'stb.ondemand.detailedscreen.synopsys.seefull': 'see full',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.guide': 'To purchase this event please enter pincode',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.info': 'If you forgot your pin please contact your provider at xxxxx to change your pincode',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.topright': 'Purchasing',
  'stb.ondemand.genre.clearselection': 'Clear selection',
  'stb.ondemand.genre.description': 'Description',
  'stb.ondemand.landingpage.recentlyaddedkids.mostpopular.subtitle': 'The most popular',
  'stb.ondemand.renthd.action': 'Rent hd',
  'stb.settings.help': 'help',
  'stb.settings.help.cutv': 'cutv',
  'stb.settings.help.cutv.description': 'description',
  'stb.settings.help.cutv.question': 'question',
  'stb.settings.help.description': 'Help description',
  'stb.settings.help.faq': 'faq',
  'stb.settings.help.faq.description': 'description',
  'stb.settings.help.faq.question': 'question',
  'stb.settings.help.faq.question.video': 'see full',
  'stb.settings.help.ondemand': 'On demand',
  'stb.settings.help.ondemand.description': 'description',
  'stb.settings.help.ondemand.question': 'questions',
  'stb.settings.help.problem': 'problem',
  'stb.settings.help.problem.autodetect': 'autodetect',
  'stb.settings.help.problem.autodetect.description': 'description',
  'stb.settings.help.problem.autodetect.networkspeed': 'network speed',
  'stb.settings.help.problem.autodetect.networkstatus': 'Network status',
  'stb.settings.help.problem.autodetect.serviceprovider': 'service provider',
  'stb.settings.help.problem.autodetect.subscription': 'subscription',
  'stb.settings.help.problem.debug': 'debug',
  'stb.settings.help.problem.debug.description': 'description',
  'stb.settings.help.problem.debug.sendlog': 'send log',
  'stb.settings.help.problem.debug.status': 'status',
  'stb.settings.help.problem.description': 'description',
  'stb.settings.help.system': 'system',
  'stb.settings.help.system.description': 'description',
  'stb.settings.help.system.question': 'questions',
  'stb.settings.help.tv': 'tv',
  'stb.settings.help.tv.question': 'question',
  'stb.settings.personal': 'Personal',
  'stb.settings.personal.account': 'Account',
  'stb.settings.personal.account.buyerid': 'Buyer ID',
  'stb.settings.personal.account.contractnumber': 'Contract number',
  'stb.settings.personal.account.description': 'Description',
  'stb.settings.personal.account.subscriptionpackage': 'subscription Package',
  'stb.settings.personal.favorites': 'Favorites',
  'stb.settings.personal.favorites.description': 'Description',
  'stb.settings.personal.favorites.radiostationlists': 'radio station lists',
  'stb.settings.personal.favorites.tvlists': 'TV lists',
  'stb.settings.personal.favorites.tvlists.cancel': 'Cancel',
  'stb.settings.personal.favorites.tvlists.categories': 'Categories',
  'stb.settings.personal.favorites.tvlists.categories.cancel': 'Cancel',
  'stb.settings.personal.favorites.tvlists.categories.description': 'Choose preffered category',
  'stb.settings.personal.favorites.tvlists.delete': 'Delete',
  'stb.settings.personal.favorites.tvlists.edit': 'Edit',
  'stb.settings.personal.favorites.tvlists.edit.description': 'Description',
  'stb.settings.personal.favorites.tvlists.newlist': 'New list',
  'stb.settings.personal.favorites.tvlists.newlist.button.ok': 'Ok (sada search button)',
  'stb.settings.personal.favorites.tvlists.newlist.name': 'Name of the new list',
  'stb.settings.personal.favorites.tvlists.newlist.section.alltv.navigation': 'All TV',
  'stb.settings.personal.favorites.tvlists.newlist.section.newlist': 'New list',
  'stb.settings.personal.favorites.tvlists.rename': 'Rename',
  'stb.settings.personal.favorites.tvlists.section.alltv': 'All TV',
  'stb.settings.personal.language': 'language',
  'stb.settings.personal.language.audiotype': 'select your preferred audio type',
  'stb.settings.personal.language.audiotype.description': 'description',
  'stb.settings.personal.language.audiotype.dolby': 'dolby',
  'stb.settings.personal.language.audiotype.stereo': 'stereo',
  'stb.settings.personal.language.description': 'description',
  'stb.settings.personal.language.firstaudio': 'first audio language',
  'stb.settings.personal.language.firstaudio.cancel': 'cancel',
  'stb.settings.personal.language.firstaudio.description': 'select your preferred audio language',
  'stb.settings.personal.language.interface': 'interface language',
  'stb.settings.personal.language.interface.cancel': 'cancel',
  'stb.settings.personal.language.interface.description': 'select the language for the application',
  'stb.settings.personal.language.secondaudio': 'second audio language',
  'stb.settings.personal.language.secondaudio.cancel': 'cancel',
  'stb.settings.personal.language.secondaudio.description': 'select your second preferred audio language',
  'stb.settings.personal.pin': 'pin',
  'stb.settings.personal.pin.description': 'description',
  'stb.settings.personal.pin.disable': 'disable',
  'stb.settings.personal.pin.enable': 'enable',
  'stb.settings.personal.pin.information': 'If you forgot your PIN please contact your provider at xxxx to change your password',
  'stb.settings.personal.pin.title': 'enter your pin',
  'stb.settings.personal.pin.title.topright': 'pin title',
  'stb.settings.personal.reminders': 'Reminders',
  'stb.settings.personal.reminders.cancel': 'cancel',
  'stb.settings.personal.reminders.description': 'Description',
  'stb.settings.personal.reminders.onevent': 'On event time',
  'stb.settings.personal.reminders.timebefore': 'X min before',
  'stb.settings.personal.summary': 'Summary',
  'stb.settings.personal.summary.description': 'Description',
  'stb.settings.personal.summary.deviceid': 'Devce ID',
  'stb.settings.personal.summary.devicemodel': 'Device Model',
  'stb.settings.personal.summary.language': 'language',
  'stb.settings.personal.summary.networkstatus': 'Network status',
  'stb.settings.personal.summary.videoquality': 'video quality',
  'stb.settings.personal.timezone': 'timezone',
  'stb.settings.personal.timezone.0': '0',
  'stb.settings.personal.timezone.auto': 'auto',
  'stb.settings.personal.timezone.cancel': 'cancel',
  'stb.settings.personal.timezone.description': 'adjust the device to the timezone where you are located',
  'stb.settings.personal.timezone.gmt-': 'gmt-',
  'stb.settings.personal.timezone.gmt+': 'gmt+',
  'stb.settings.systempreferences': 'system preferences',
  'stb.settings.systempreferences.about': 'about',
  'stb.settings.systempreferences.about.description': 'id, serial number and mac address information',
  'stb.settings.systempreferences.about.id': 'id',
  'stb.settings.systempreferences.about.macaddress': 'mac address',
  'stb.settings.systempreferences.about.serialnumber': 'serial number',
  'stb.settings.systempreferences.demomode': 'demo mode',
  'stb.settings.systempreferences.demomode.cancel': 'cancel',
  'stb.settings.systempreferences.demomode.description': 'optimise the display for retail use',
  'stb.settings.systempreferences.demomode.off': 'off',
  'stb.settings.systempreferences.demomode.on': 'on',
  'stb.settings.systempreferences.hdmiyuv': 'hdmi-yuv',
  'stb.settings.systempreferences.hdmiyuvoutput': 'hdmi-yuv output',
  'stb.settings.systempreferences.hdmiyuvoutput.description': 'select how 4:3 video should be displayed on a 16:9 TV',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion': '4:3 video conversion on 16:9 tv',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.cancel': 'cancel',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.pillarbox': 'pillar box',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.stretched': 'stretched',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.zoom': 'zoom',
  'stb.settings.systempreferences.miscellaneous': 'miscellaneous',
  'stb.settings.systempreferences.miscellaneous.description': 'select after how many seconds the zap banner should disappear',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent': 'zap banner on new event',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.cancel': 'cancel',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.description': 'select appearance of zap banner every time a new program starts',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.no': 'no',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.yes': 'yes',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin': 'remember the pincode',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.cancel': 'cancel',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.description': 'select the default timeout value for this option',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.h': 'h',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.mins': 'min',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.untilh': 'until xh',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.untilreboot': 'until reboot',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout': 'zap banner time out',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.cancel': 'cancel',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.description': 'Select after how many seconds the zap banner should disappear',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.seconds': 's',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.until': 'display unitl closed by viewer',
  'stb.settings.systempreferences.network': 'network',
  'stb.settings.systempreferences.network.checkconnection': 'Check connection',
  'stb.settings.systempreferences.network.checkconnection.connecting': 'Connecting',
  'stb.settings.systempreferences.network.checkconnection.connecting.description': 'This may take a couple of minutes to complete',
  'stb.settings.systempreferences.network.checkconnection.connectionresults': 'Connection results',
  'stb.settings.systempreferences.network.checkconnection.connectionresults.description': 'if you cannot access content, please ask the service provider',
  'stb.settings.systempreferences.network.checkconnection.internetaccess': 'Internet access',
  'stb.settings.systempreferences.network.checkconnection.localaccess': 'Local access',
  'stb.settings.systempreferences.network.checkconnection.wirelessdevice': 'Wireless device on TV',
  'stb.settings.systempreferences.network.description': '',
  'stb.settings.systempreferences.network.networkstatus': 'Network status',
  'stb.settings.systempreferences.network.networkstatus.defaultgateway': 'default gateway',
  'stb.settings.systempreferences.network.networkstatus.description': 'view info about network status',
  'stb.settings.systempreferences.network.networkstatus.ipaddresssetting': 'IP address setting',
  'stb.settings.systempreferences.network.networkstatus.ipadress': 'IP address ',
  'stb.settings.systempreferences.network.networkstatus.ipv6': 'IPv6',
  'stb.settings.systempreferences.network.networkstatus.macaddress': 'mac address',
  'stb.settings.systempreferences.network.networkstatus.primarydns': 'primary dns',
  'stb.settings.systempreferences.network.networkstatus.secondarydns': 'secondary dns',
  'stb.settings.systempreferences.network.networkstatus.subnetmask': 'subnet mask',
  'stb.settings.systempreferences.network.speedtest': 'speed test',
  'stb.settings.systempreferences.network.speedtest.current speed': 'current speed',
  'stb.settings.systempreferences.network.speedtest.description': 'Press ok for measuring speed',
  'stb.settings.systempreferences.network.speedtest.max': 'max',
  'stb.settings.systempreferences.network.speedtest.min': 'min',
  'stb.settings.systempreferences.network.speedtest.ping': 'ping',
  'stb.settings.systempreferences.network.speedtest.server': 'server',
  'stb.settings.systempreferences.quality': 'quality',
  'stb.settings.systempreferences.quality.auto': 'auto',
  'stb.settings.systempreferences.quality.bps': 'bps',
  'stb.settings.systempreferences.quality.cancel': 'cancel',
  'stb.settings.systempreferences.quality.description': 'ajdust quality of the channel',
  'stb.settings.systempreferences.software': 'software',
  'stb.settings.systempreferences.software.application version': 'application version',
  'stb.settings.systempreferences.software.description': 'current application version and tv model',
  'stb.settings.systempreferences.software.tv model': 'tv model',
  'tablet.guide.alltv.favorites.newlist.title': 'Name of the new list'
}
