export default {
  'general.filter': 'filter',
  'general.filter.actor': 'prema glumcima',
  'general.filter.availability': 'prema dostupnosti',
  'general.filter.availability.available': 'dostupno',
  'general.filter.availability.unavailable': 'nedostupno',
  'general.filter.clearfilter': 'obriÅ¡i filter',
  'general.filter.contentrating': 'Ocena sadrÅ¾aja',
  'general.filter.director': 'ReÅ¾iser',
  'general.filter.year': 'Godina',
  'general.navigation.guide': 'program',
  'general.navigation.home': 'poÄetna',
  'general.navigation.mylibrary': 'Moja biblioteka',
  'general.navigation.ondemand': 'video klub',
  'general.navigation.settings': 'PodeÅ¡avanja',
  'general.search.cutv': 'cutv',
  'general.search.noresults': 'Nema rezultata',
  'general.search.ondemand': 'video klub',
  'general.search.searchcontent': 'pretraga',
  'general.search.searchcontent.search.action': 'pretraga',
  'general.search.tv': 'TV',
  'general.seeall': 'vidi sve',
  'general.sort': 'sortiraj ',
  'general.sort.az': 'A-Z',
  'general.sort.channel': 'prema kanalima',
  'general.sort.clearsort': 'obriÅ¡i sortiranje',
  'general.sort.date': 'prema datumu',
  'general.sort.dateadded': 'prema datumu dodavanja',
  'general.sort.duration': 'prema trajanju',
  'general.sort.event': 'prema dogaÄ‘aju',
  'general.sort.mostlistened': 'najsluÅ¡anije',
  'general.sort.mostwatched': 'najgledanije',
  'general.sort.rating': 'prema oceni',
  'general.sort.recommended': 'prema preporukama',
  'general.sort.releasedate': 'prema datumu objave',
  'general.sort.time': 'vreme',
  'guide.alltv': 'svi TV kanali',
  'guide.alltv.favorites.choosefilter': 'filter',
  'guide.alltv.favorites.customlist.delete': 'ObriÅ¡i',
  'guide.alltv.favorites.edit': 'izmeni',
  'guide.alltv.favorites.filter.searchchannel': 'pretraÅ¾i kanale',
  'guide.alltv.favorites.ok': 'OK',
  'guide.alltv.favorites.radio': 'Radio',
  'guide.alltv.favorites.tv': 'TV',
  'guide.calendar.date': 'Datum',
  'guide.calendar.date.dayname': 'Dani ',
  'guide.calendar.datetimeslot': 'dan i doba dana',
  'guide.calendar.datetimeslot.ok': 'OK',
  'guide.calendar.dayname': 'Danas (dani)',
  'guide.calendar.timeslot.afternoon': 'Popodne',
  'guide.calendar.timeslot.evening': 'PredveÄe',
  'guide.calendar.timeslot.latenight': 'Kasno uveÄe',
  'guide.calendar.timeslot.morning': 'Ujutru',
  'guide.eventplaying.back': 'Nazad',
  'guide.eventplaying.connecttodevice': 'PoveÅ¾i sa ureÄ‘ajem',
  'guide.eventplaying.playevent': 'gledaj dogaÄ‘aj',
  'guide.eventplaying.playevent.playondevice': 'gledaj na ureÄ‘aju',
  'guide.eventplaying.playevent.playondevice.description': 'Opis koji ide uz gledaj na ureÄ‘aju',
  'guide.eventplaying.playevent.playondevice.disconnect': 'prekini vezu sa ureÄ‘ajem',
  'guide.eventplaying.playevent.playondevice.title': 'Naziv',
  'guide.live': 'UÅ¾ivo',
  'guide.nowplaying': 'sada',
  'guide.nowtv': 'sada na TV-u',
  'guide.nowtv.before': 'Pre',
  'guide.nowtv.event.details.cast': 'uloge',
  'guide.nowtv.event.details.director': 'reÅ¾iser',
  'guide.nowtv.event.details.download': 'preuzeti',
  'guide.nowtv.event.details.favorites': 'omiljeno',
  'guide.nowtv.event.details.language': 'jezik',
  'guide.nowtv.event.details.noinfo': 'nema informacija',
  'guide.nowtv.event.details.record': 'snimi',
  'guide.nowtv.next': 'sledeÄ‡e',
  'guide.nowtv.now': 'sada',
  'guide.radio.allradio': 'Sve radio stanice',
  'home.apps': 'aplikacije',
  'home.notifications.message.delete': 'obriÅ¡i',
  'home.notifications.newmessages': 'nove poruke',
  'home.notifications.nomessages': 'nema poruka',
  'home.nowontv': 'sada na TV-u',
  'home.ondemand': 'video klub',
  'home.radio': 'radio stanice',
  'home.view.foryou': 'preporuÄeno',
  'home.view.viewall': 'vidi sve',
  'login.createpincode.done': 'u redu',
  'login.createpincode.enterpincode': 'unesite pin kod',
  'login.createpincode.reenterpincode': 'ponovo unesite pin kod',
  'login.createpincode.skip': 'preskoÄi',
  'login.createpincode.userpincode': 'korisniÄki pin kod',
  'login.createprofile.addphoto': 'dodaj sliku',
  'login.createprofile.dateofbirth': 'datum roÄ‘enja',
  'login.createprofile.done': 'u redu',
  'login.createprofile.enablepincode': 'omoguÄ‡i pin kod',
  'login.createprofile.error': 'greÅ¡ka u kreiranju profila',
  'login.createprofile.genderselection': 'pol',
  'login.createprofile.genderselection.female': 'Å¾',
  'login.createprofile.genderselection.male': 'm',
  'login.createprofile.infotext': 'kako kreirati profil',
  'login.createprofile.name': 'ime',
  'login.createprofile.password': 'Å¡ifra',
  'login.createprofile.save': 'saÄuvaj',
  'login.createprofile.signin': 'uloguj se',
  'login.createprofile.username': 'korisniÄko ime',
  'login.createprofile.userprofile': 'korisniÄki profil',
  'login.editprofile.changephoto': 'promenite sliku',
  'login.editprofile.changepin.back': 'nazad',
  'login.editprofile.changepin.disablepin': 'onemoguÄ‡i',
  'login.editprofile.changepin.done': 'u redu',
  'login.editprofile.changepin.enternew': 'unesite novi pin kod',
  'login.editprofile.changepin.reenternew': 'ponovo unesite novi pin kod',
  'login.editprofile.changepin.userpincode': 'korisniÄki pin kod',
  'login.editprofile.changepincode': 'promenite pin kod',
  'login.editprofile.delete': 'obriÅ¡i',
  'login.editprofile.done': 'u redu',
  'login.editprofile.pin.action.unlock': 'otkljuÄaj',
  'login.editprofile.pin.profilelogin.description': 'unesite pin kod da biste otkljuÄali',
  'login.editprofile.pin.profilelogin.title': 'Prijava na profil',
  'login.editprofile.save': 'saÄuvaj',
  'login.introductionscreen.next': 'sledeÄ‡i',
  'login.introductionscreen.signin': 'ulogujte se',
  'login.language.selectlanguage': 'izaberite jezik',
  'login.loading': 'UÄitavanje',
  'login.whoswatching': 'Ko gleda',
  'login.whoswatching.addprofile': 'Dodajte profil',
  'login.whoswatching.editprofile': 'izmeni',
  'login.whoswatching.editprofile.title': 'izmeni profil',
  'login.whoswatching.family': 'nastavi porodiÄno',
  'message.guide.action.contact': 'kontaktiraj',
  'message.guide.action.unlock': 'otkljuÄajte',
  'message.guide.action.view': 'Pogledajte',
  'message.guide.description.enterpincode': 'Da biste otkljuÄali unesite pin kod',
  'message.guide.description.problem.channelunavailable': 'Izabrani kanal nije dostupan u vaÅ¡oj zemlji. Za dodatne informacije molimo vas pozovite call centar',
  'message.guide.description.problem.copyrightissue': 'SadrÅ¾aj nije moguÄ‡e prikazati zbog autorskih prava. Za viÅ¡e informacija, pozovite korisniÄki servis.',
  'message.guide.description.problem.notsubsribed.channel': 'Niste pretplaÄ‡eni na ovaj kanal. Za viÅ¡e informacija, molimo vas pozovite korisniÄki servis.',
  'message.guide.description.problem.notsubsribed.service': 'Niste pretplaÄ‡eni na ovu uslugu. Za viÅ¡e informacija, molimo vas pozovite korisniÄki servis.',
  'message.guide.description.problem.signalerror': 'DoÅ¡lo je do greÅ¡ke prilikom primanja signala. Molimo vas pozovite korisniÄki servis.',
  'message.guide.description.problem.subscriptionexpired': 'Pretplata vam je istekla. Kako biste je obnovili, pozovite korisniÄki servis.',
  'message.guide.title.info': 'Informacija',
  'message.guide.title.lockedchannel': 'Kanal je zakljuÄan',
  'message.guide.title.reminders': 'Podsetnik',
  'mylibrary.download': 'Preuzmi',
  'mylibrary.download.disksize': 'kapacitet diska',
  'mylibrary.download.downloadedondemand': 'preuzeto iz video kluba',
  'mylibrary.download.downloadedtvcontent': 'Preuzet TV sadrÅ¾aj',
  'mylibrary.dvr': 'u oblaku',
  'mylibrary.dvr.completedrecordings': 'ZavrÅ¡ena snimanja',
  'mylibrary.dvr.memorysize': 'VeliÄina memorije',
  'mylibrary.dvr.ongoingrecordings': 'snimanja u toku',
  'mylibrary.dvr.scheduledrecordings': 'Zakazana snimanja',
  'mylibrary.favorites': 'omiljeno',
  'mylibrary.favorites.ondemand': 'video klub',
  'mylibrary.favorites.tvevents': 'TV dogaÄ‘aji',
  'mylibrary.less': 'prikaÅ¾i manje',
  'mylibrary.more': 'prikaÅ¾i viÅ¡e',
  'mylibrary.nodownload.description': 'Opis za Nema preuzetog sadrÅ¾aja',
  'mylibrary.nodownload.title': 'nema preuzetog sadrÅ¾aja',
  'mylibrary.nodvr.description': 'opis za nema sadrÅ¾aja u oblaku ',
  'mylibrary.nodvr.title': 'nema sadrzaja u oblaku',
  'mylibrary.nofavorites.description': 'opis za nema omiljenog sadrÅ¾aja',
  'mylibrary.nofavorites.title': 'nema omiljenog sadrÅ¾aja',
  'mylibrary.nopurchase.description': 'opis za nema kupljenog sadrÅ¾aja',
  'mylibrary.nopurchase.title': 'nema kupljenog sadrÅ¾aja',
  'mylibrary.noreminder.description': 'opis za nema podsetnika',
  'mylibrary.noreminder.title': 'Nema podsetnika',
  'mylibrary.purchase': 'kupljeno',
  'mylibrary.purchase.available': 'dostupno',
  'mylibrary.purchase.expired': 'isteklo',
  'mylibrary.reminder': 'podsetnik',
  'ondemand.categories': 'kategorije',
  'ondemand.continuewatching.seeall.catalogues': 'katalozi',
  'ondemand.continuewatching.seeall.catalogues.clearselction': 'obriÅ¡i izabrano',
  'ondemand.detailedscreen.availablefor.duration': 'dostupno za iznajmljivanje do dd.mm.yyyy.',
  'ondemand.detailedscreen.availablein.duration': 'dostupno narednih 48h',
  'ondemand.detailedscreen.cast': 'uloge',
  'ondemand.detailedscreen.castandcrew': 'uloge ',
  'ondemand.detailedscreen.director': 'reÅ¾iser',
  'ondemand.detailedscreen.favorites': 'Omiljeno',
  'ondemand.detailedscreen.hd': 'hd',
  'ondemand.detailedscreen.language': 'jezik',
  'ondemand.detailedscreen.morelikethis': 'sliÄno',
  'ondemand.detailedscreen.notsubscribed': 'niste pretplaÄ‡eni',
  'ondemand.detailedscreen.notsubscribed.information.action.ok': 'ok',
  'ondemand.detailedscreen.notsubscribed.information.description': 'Niste pretplaÄ‡eni na ovaj katalog. Molimo vas pozovite korisniÄki centar ili posetite portal.',
  'ondemand.detailedscreen.notsubscribed.information.title': 'informacija vezana za pretplatu',
  'ondemand.detailedscreen.price': 'hd cena/sd cena',
  'ondemand.detailedscreen.price.currency': 'valuta',
  'ondemand.detailedscreen.rent': 'iznajmi/kupi',
  'ondemand.detailedscreen.rentfor.currency.title': 'Iznajmi/kupi za X RSD',
  'ondemand.detailedscreen.rentfor.description': 'Iznajmi na 2 dana. Dostupno za iznajmljivanje do dd.mm.yyyy.',
  'ondemand.detailedscreen.rentfor.duration': 'iznajmi na x dana',
  'ondemand.detailedscreen.sd': 'sd',
  'ondemand.detailedscreen.seasons': 'sezone',
  'ondemand.detailedscreen.seasons.back': 'nazad',
  'ondemand.detailedscreen.subscribed': 'pretplaÄ‡eni ste',
  'ondemand.detailedscreen.synopsys': 'sinopsis',
  'ondemand.detailedscreen.synopsys.more': 'joÅ¡',
  'ondemand.detailedscreen.titles': 'nazivi',
  'ondemand.detailedscreen.trailer': 'trejler',
  'ondemand.detailedscreen.transitionalscreen.purchasing.description': 'Kako biste kupili ovaj dogaÄ‘aj molimo vas posetite www.d3go.tv ili to uradite preko vaÅ¡eg STB-a',
  'ondemand.detailedscreen.transitionalscreen.purchasing.ok': 'OK',
  'ondemand.detailedscreen.transitionalscreen.purchasing.title': 'kupovina',
  'ondemand.detailedscreen.watch': 'Gledaj',
  'ondemand.genre': 'Å¾anr',
  'ondemand.landingpage.allcatalogues': 'Svi katalozi',
  'ondemand.landingpage.continuewatching': 'Nastavi gledanje',
  'ondemand.landingpage.recentlyaddedkids.title': 'poslednje dodato u kategoriji deca',
  'ondemand.landingpage.recentlyaddedmovies': 'poslednje dodato u kategoriji filmovi',
  'ondemand.landingpage.recentlyaddedseries': 'poslednje dodato u kategoriji serije',
  'ondemand.landingpage.rentandwatch': 'iznajmi i gledaj',
  'phone.guide.alltv.favorites.newlist.action.save': 'saÄuvaj',
  'phone.guide.alltv.favorites.newlist.description': 'ime liste omiljenih kanala',
  'phone.guide.alltv.favorites.newlist.title': 'Nova lista',
  'settings.about': 'O aplikaciji',
  'settings.about.aboutsection': 'O aplikaciji',
  'settings.about.aboutsection.version': 'verzija',
  'settings.account': 'nalog',
  'settings.account.accountsection': 'nalog',
  'settings.account.accountsection.description': 'Trenutno ste prijavljeni sa ovim nalogom',
  'settings.account.signout': 'odjavite se',
  'settings.changepin': 'promenite pin kod',
  'settings.changepin.changepinsection': 'promenite pin kod',
  'settings.changepin.changepinsection.confirmnew': 'napravite novi pin kod',
  'settings.changepin.changepinsection.description': 'Master pin kod mora biti Äetvorocifren. Neophodan je kako biste gledali program za odrasle.',
  'settings.changepin.changepinsection.newpin': 'novi pin kod',
  'settings.changepin.changepinsection.ok': 'ok',
  'settings.changepin.changepinsection.oldpin': 'stari pin kod',
  'settings.devicemanagement': 'upravljanje ureÄ‘ajima',
  'settings.devicemanagement.description': 'MoÅ¾ete da promeneite ureÄ‘aje najviÅ¡e 5 puta meseÄno. Ovde je prikazan preostali broj promena.',
  'settings.devicemanagement.done': 'u redu',
  'settings.devicemanagement.refresh': 'osveÅ¾i',
  'settings.devicemanagement.registereddeviccessection': 'Registrovani ureÄ‘aji',
  'settings.download': 'Preuzeto',
  'settings.download.resolutionsection': 'rezolucija',
  'settings.download.resolutionsection.high': 'visoka',
  'settings.download.resolutionsection.low': 'niska',
  'settings.download.resolutionsection.medium': 'srednja',
  'settings.download.storagelimitsection': 'OgraniÄenje u skladiÅ¡tu',
  'settings.download.storagelimitsection.nolimit': 'nema ograniÄenja',
  'settings.download.storagelimitsection.nolimit.availability': 'X GB dostupno',
  'settings.download.storagelimitsection.nolimit.usage': 'X MB iskoriÅ¡Ä‡eno',
  'settings.dvr': 'U oblaku',
  'settings.dvr.endsection': 'ZavrÅ¡ava se ',
  'settings.dvr.endsection.oneventtime': 'u skladu sa dogaÄ‘ajem',
  'settings.dvr.endsection.timeafter': 'X min ranije',
  'settings.dvr.startsection': 'PoÄinje',
  'settings.dvr.startsection.oneventtime': 'u skladu sa dogaÄ‘ajem',
  'settings.dvr.startsection.timebefore': 'X min ranije',
  'settings.help': 'PomoÄ‡',
  'settings.help.callcenternumber': 'Broj korisniÄkog centra',
  'settings.help.website': 'vebsajt',
  'settings.language': 'jezik',
  'settings.reminder': 'podsetnik',
  'settings.reminder.remindersection': 'podsetnik',
  'settings.reminder.remindersection.onevettime': 'u skladu sa dogaÄ‘ajem',
  'settings.reminder.remindersection.timebefore': 'X min ranije',
  'settings.summary': 'SaÅ¾etak',
  'settings.summary.buyerid': 'ID kupca',
  'settings.summary.contactnumber': 'broj ugovora',
  'settings.summary.deviceid': 'ID ureÄ‘aja',
  'settings.summary.devicemodel': 'model ureÄ‘aja',
  'settings.summary.language': 'jezik',
  'settings.summary.networkstatus': 'status mreÅ¾e',
  'settings.summary.subscriptionpackage': 'Pretplata',
  'settings.summary.videoquality': 'kvalitet videa',
  'settings.videoquality': 'kvalitet videa',
  'settings.videoquality.auto': 'auto',
  'settings.videoquality.bps': 'bps',
  'settings.videoquality.cellular': 'mobilna mreÅ¾a ',
  'settings.videoquality.cellular.auto': 'auto',
  'settings.videoquality.cellular.bps': 'bps',
  'settings.videoquality.wifi': 'wifi',
  'stb.general.navigation.help': 'pomoÄ‡',
  'stb.general.navigation.profilename': 'ime profila',
  'stb.general.sort.description': 'opis koji ide za ime profila',
  'stb.guide.categories': 'kategorije',
  'stb.guide.categories.clear categories': 'obriÅ¡i kategoriju',
  'stb.guide.categories.description': 'opis koji ide uz kategorije',
  'stb.guide.nowtv': 'Sada na TV-u',
  'stb.guide.nowtv.details.reminder': 'podsetnik',
  'stb.guide.nowtv.details.startover': 'gledajte ispoÄetka',
  'stb.guide.nowtv.details.watch': 'gledajte',
  'stb.guide.nowtv.event.details.description': 'opis',
  'stb.guide.nowtv.event.details.seefull': 'pogledaj sve',
  'stb.guide.nowtv.event.details.starring': 'glavne uloge',
  'stb.guide.nowtv.event.details.synopsys': 'sinopsis',
  'stb.guide.radio.next': 'sledeÄ‡e',
  'stb.guide.radio.youarelistening': 'SluÅ¡ate',
  'stb.guide.radiostations': 'radio stanice',
  'stb.guide.radiostations.genre': 'Å¾anr',
  'stb.guide.tvchannels': 'TV kanalI',
  'stb.home.apps.topfree.mostpopular.subtitle': 'najpopularnije',
  'stb.home.apps.topfree.title': 'najpopularnije besplatne aplikacije',
  'stb.home.notifications.topright': 'obaveÅ¡tenja',
  'stb.home.ondemand.videoondemand.mostpopular.subtitle': 'najpopularnije',
  'stb.home.ondemand.videoondemand.title': 'Video klub',
  'stb.home.title.topright': 'PoÄetna',
  'stb.home.view.general': 'OpÅ¡te',
  'stb.loading.error.networkerror': '403 - problemi sa mreÅ¾om ',
  'stb.loading.error.systemerror': '407 - sistemska greÅ¡ka',
  'stb.loading.update.error': '405 - greÅ¡ka nadogradnje',
  'stb.loading.update.inprogress': 'nadogradnja u toku',
  'stb.login.activation.activationcode': 'aktivacioni kod',
  'stb.login.activation.errormessage.action.log': 'log (prikupljeni podaci)',
  'stb.login.activation.errormessage.action.retry': 'pokuÅ¡aj ponovo',
  'stb.login.activation.errormessage.description': 'opis greÅ¡ke prilikom aktivacije',
  'stb.login.activation.errormessage.title': 'Naziv greÅ¡ke prilikom aktivacije',
  'stb.login.activation.instructions.item1': 'Posetite x.com (url sajta) na vaÅ¡em raÄunaru ili mobilnom ureÄ‘aju',
  'stb.login.activation.instructions.item2': 'Unesite aktivacioni kod kada se pojavi polje',
  'stb.login.activation.instructions.item3': 'joÅ¡ neki tekst vezan za aktivaciju',
  'stb.login.activation.updateinfo': 'Ovaj ekran Ä‡e se automatski osveÅ¾iti nakon Å¡to poveÅ¾ete ureÄ‘aj sa vaÅ¡im nalogom',
  'stb.mylibrary.dvr.detailedscreen.delete': 'obriÅ¡ite',
  'stb.mylibrary.dvr.disksize': 'kapacitet diska',
  'stb.ondemand.detailedscreen.markasunwatched': 'OznaÄi kao neodgledano',
  'stb.ondemand.detailedscreen.markaswatched': 'OznaÄi kao odgledano',
  'stb.ondemand.detailedscreen.more': 'joÅ¡',
  'stb.ondemand.detailedscreen.qualityrentedfor': 'SD kvalitet iznajmljen za X RSD',
  'stb.ondemand.detailedscreen.rentfor.cancel': 'otkaÅ¾i',
  'stb.ondemand.detailedscreen.rentquality.button': 'iznajmi HD/SD',
  'stb.ondemand.detailedscreen.starring': 'Glavne uloge',
  'stb.ondemand.detailedscreen.synopsys.seefull': 'vidi sve',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.guide': 'Kako biste kupili ovaj sadrÅ¾aj unesite pin kod',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.info': 'Ukoliko ste zaboravili vaÅ¡ pin kod, molimo vas kontaktirajte provajdera kako biste promenili pincode.',
  'stb.ondemand.detailedscreen.transitionalscreen.purchasing.topright': 'Iznajmljivanje/kupovina',
  'stb.ondemand.genre.clearselection': 'obriÅ¡i izabrano',
  'stb.ondemand.genre.description': 'Opis koji ide ispod Å¾anra',
  'stb.ondemand.landingpage.recentlyaddedkids.mostpopular.subtitle': 'najpopularnije',
  'stb.ondemand.renthd.action': 'iznajmite HD',
  'stb.settings.help': 'PomoÄ‡',
  'stb.settings.help.cutv': 'cutv',
  'stb.settings.help.cutv.description': 'opis koji ide uz cutv',
  'stb.settings.help.cutv.question': 'pitanja koja idu uz cutv',
  'stb.settings.help.description': 'opis za sekciju pomoÄ‡',
  'stb.settings.help.faq': 'faq',
  'stb.settings.help.faq.description': 'ovde ide opis Å¡ta je faq',
  'stb.settings.help.faq.question': 'ovde idu pitanja uz faq',
  'stb.settings.help.faq.question.video': 'vidi sve',
  'stb.settings.help.ondemand': 'video klub',
  'stb.settings.help.ondemand.description': 'opis koji ide uz video klub',
  'stb.settings.help.ondemand.question': 'pitanja koja idu uz video klub',
  'stb.settings.help.problem': 'Problem',
  'stb.settings.help.problem.autodetect': 'automatska detekcija',
  'stb.settings.help.problem.autodetect.description': 'opis koji ide uz automatsku detekciju',
  'stb.settings.help.problem.autodetect.networkspeed': 'brzina mreÅ¾e',
  'stb.settings.help.problem.autodetect.networkstatus': 'status mreÅ¾e',
  'stb.settings.help.problem.autodetect.serviceprovider': 'servis provajder',
  'stb.settings.help.problem.autodetect.subscription': 'pretplata',
  'stb.settings.help.problem.debug': 'pronalaÅ¾enje i otklanjanje greÅ¡aka',
  'stb.settings.help.problem.debug.description': 'opis koji ide uz pronalaÅ¾enje i otklanjanje greÅ¡aka',
  'stb.settings.help.problem.debug.sendlog': 'poÅ¡alji prikupljene podatke',
  'stb.settings.help.problem.debug.status': 'status ',
  'stb.settings.help.problem.description': 'opis koji ide uz problem sekciju',
  'stb.settings.help.system': 'sistem',
  'stb.settings.help.system.description': 'opis koji ide uz sistem sekciju',
  'stb.settings.help.system.question': 'pitanja koja idu u sistem sekciju',
  'stb.settings.help.tv': 'TV',
  'stb.settings.help.tv.question': 'pitanja koja idu uz TV sekciju',
  'stb.settings.personal': 'KorisniÄka podeÅ¡avanja',
  'stb.settings.personal.account': 'nalog',
  'stb.settings.personal.account.buyerid': 'ID kupca',
  'stb.settings.personal.account.contractnumber': 'broj ugovora',
  'stb.settings.personal.account.description': 'opis koji ide uz sekciju nalog',
  'stb.settings.personal.account.subscriptionpackage': 'Pretplata',
  'stb.settings.personal.favorites': 'omiljeno',
  'stb.settings.personal.favorites.description': 'opis koji ide uz sekciju omiljeno',
  'stb.settings.personal.favorites.radiostationlists': 'lista radio stanica',
  'stb.settings.personal.favorites.tvlists': 'lista TV kanala',
  'stb.settings.personal.favorites.tvlists.cancel': 'otkaÅ¾i',
  'stb.settings.personal.favorites.tvlists.categories': 'kategorije',
  'stb.settings.personal.favorites.tvlists.categories.cancel': 'otkaÅ¾i',
  'stb.settings.personal.favorites.tvlists.categories.description': 'izaberite Å¾eljenu kategoriju',
  'stb.settings.personal.favorites.tvlists.delete': 'obriÅ¡ite',
  'stb.settings.personal.favorites.tvlists.edit': 'izmeni',
  'stb.settings.personal.favorites.tvlists.edit.description': 'opis koji ide uz sekciju izmeni',
  'stb.settings.personal.favorites.tvlists.newlist': 'nova lista',
  'stb.settings.personal.favorites.tvlists.newlist.button.ok': 'OK',
  'stb.settings.personal.favorites.tvlists.newlist.name': 'ime nove liste',
  'stb.settings.personal.favorites.tvlists.newlist.section.alltv.navigation': 'svi TV kanali',
  'stb.settings.personal.favorites.tvlists.newlist.section.newlist': 'nova lista',
  'stb.settings.personal.favorites.tvlists.rename': 'preimenuj',
  'stb.settings.personal.favorites.tvlists.section.alltv': 'svi tv kanali',
  'stb.settings.personal.language': 'jezik',
  'stb.settings.personal.language.audiotype': 'Izaberi Å¾eljeni tip zvuka',
  'stb.settings.personal.language.audiotype.description': 'opis koji ide uz sekciju tip zvuka',
  'stb.settings.personal.language.audiotype.dolby': 'dolby',
  'stb.settings.personal.language.audiotype.stereo': 'stereo',
  'stb.settings.personal.language.description': 'opis za jezike',
  'stb.settings.personal.language.firstaudio': 'primarni jezik zvuka',
  'stb.settings.personal.language.firstaudio.cancel': 'otkaÅ¾i',
  'stb.settings.personal.language.firstaudio.description': 'Izaberi Å¾eljeni tip zvuka',
  'stb.settings.personal.language.interface': 'jezik interfejsa',
  'stb.settings.personal.language.interface.cancel': 'otkaÅ¾i',
  'stb.settings.personal.language.interface.description': 'Izaberite jezik aplikacije',
  'stb.settings.personal.language.secondaudio': 'sekundarni jezik zvuka',
  'stb.settings.personal.language.secondaudio.cancel': 'otkaÅ¾i',
  'stb.settings.personal.language.secondaudio.description': 'Izaberite Å¾eljeni sekundarni jezik zvuka',
  'stb.settings.personal.pin': 'pin',
  'stb.settings.personal.pin.description': 'opis koji ide uz sekciju pin',
  'stb.settings.personal.pin.disable': 'onemoguÄ‡i',
  'stb.settings.personal.pin.enable': 'omoguÄ‡i',
  'stb.settings.personal.pin.information': 'Ukoliko ste zaboravili vaÅ¡ pin, molimo vas kontaktirajte provajdera na broj kako biste promenili pin',
  'stb.settings.personal.pin.title': 'unesite vaÅ¡ pin',
  'stb.settings.personal.pin.title.topright': 'pin',
  'stb.settings.personal.reminders': 'podsetnik',
  'stb.settings.personal.reminders.cancel': 'otkaÅ¾i',
  'stb.settings.personal.reminders.description': 'opis koji ide uz sekciju podsetnik',
  'stb.settings.personal.reminders.onevent': 'u skladu sa dogaÄ‘ajem',
  'stb.settings.personal.reminders.timebefore': 'X min ranije',
  'stb.settings.personal.summary': 'saÅ¾etak',
  'stb.settings.personal.summary.description': 'opis koji ide uz sekciju saÅ¾etak',
  'stb.settings.personal.summary.deviceid': 'ID ureÄ‘aja',
  'stb.settings.personal.summary.devicemodel': 'Model ureÄ‘aja',
  'stb.settings.personal.summary.language': 'jezik',
  'stb.settings.personal.summary.networkstatus': 'status mreÅ¾e',
  'stb.settings.personal.summary.videoquality': 'video kvalitet',
  'stb.settings.personal.timezone': 'Vremenska zona',
  'stb.settings.personal.timezone.0': '0',
  'stb.settings.personal.timezone.auto': 'auto',
  'stb.settings.personal.timezone.cancel': 'otkaÅ¾i',
  'stb.settings.personal.timezone.description': 'Podesi vremensku zonu ureÄ‘aja prema lokaciji na kojoj se nalazite',
  'stb.settings.personal.timezone.gmt-': 'gmt-',
  'stb.settings.personal.timezone.gmt+': 'gmt+',
  'stb.settings.systempreferences': 'sistemska podeÅ¡avanja',
  'stb.settings.systempreferences.about': 'O sistemu',
  'stb.settings.systempreferences.about.description': 'ID, serijski broj i mac adresa',
  'stb.settings.systempreferences.about.id': 'ID',
  'stb.settings.systempreferences.about.macaddress': 'Mac adresa',
  'stb.settings.systempreferences.about.serialnumber': 'serijski broj',
  'stb.settings.systempreferences.demomode': 'demo naÄin rada',
  'stb.settings.systempreferences.demomode.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.demomode.description': 'optimizuj sliku za potrebe demonstracije',
  'stb.settings.systempreferences.demomode.off': 'iskljuÄi',
  'stb.settings.systempreferences.demomode.on': 'ukljuÄi',
  'stb.settings.systempreferences.hdmiyuv': 'hdmi-yuv',
  'stb.settings.systempreferences.hdmiyuvoutput': 'hdmi',
  'stb.settings.systempreferences.hdmiyuvoutput.description': 'izbor naÄina prilagoÄ‘avanja slike razliÄitog formata',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion': 'PrilagoÄ‘avanje slike (4:3 na 16:9)',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.pillarbox': 'dimenzija ekrana (4:3)',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.stretched': 'razvuÄeno',
  'stb.settings.systempreferences.hdmiyuvoutput.videoconversion.zoom': 'zoom',
  'stb.settings.systempreferences.miscellaneous': 'ostalo',
  'stb.settings.systempreferences.miscellaneous.description': 'izaberite za koliko sekundi info prikaz treba da nestane',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent': 'Info prikaz na novom dogaÄ‘aju',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.description': 'prikaÅ¾i info svaki put kada se promeni kanal',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.no': 'ne',
  'stb.settings.systempreferences.miscellaneous.zapbanner.onnewevent.yes': 'da',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin': 'zapamti pin kod',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.description': 'podstavi podrazumevano vreme tajmauta za ovu opciju',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.h': 'h',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.mins': 'min',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.untilh': 'do Xh',
  'stb.settings.systempreferences.miscellaneous.zapbanner.rememberpin.untilreboot': 'do restarta',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout': 'tajmaut info prikaza',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.description': 'izaberite vreme nakon kojeg Ä‡e info prikaz nestati',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.seconds': 's',
  'stb.settings.systempreferences.miscellaneous.zapbanner.timeout.until': 'prikaÅ¾i dok ga korisnik ne ugasi',
  'stb.settings.systempreferences.network': 'mreÅ¾a',
  'stb.settings.systempreferences.network.checkconnection': 'Proveri konekciju',
  'stb.settings.systempreferences.network.checkconnection.connecting': 'Povezivanje u toku',
  'stb.settings.systempreferences.network.checkconnection.connecting.description': 'Ovo moÅ¾e potrajati nekoliko minuta ',
  'stb.settings.systempreferences.network.checkconnection.connectionresults': 'Rezultati konekcije',
  'stb.settings.systempreferences.network.checkconnection.connectionresults.description': 'Ukoliko ne moÅ¾ete da pristupite sadrÅ¾aju, molimo vas kontaktirajte servis provajdera',
  'stb.settings.systempreferences.network.checkconnection.internetaccess': 'Internet pristup',
  'stb.settings.systempreferences.network.checkconnection.localaccess': 'Å½iÄni (LAN)',
  'stb.settings.systempreferences.network.checkconnection.wirelessdevice': 'BeÅ¾iÄni (Wifi)',
  'stb.settings.systempreferences.network.description': '',
  'stb.settings.systempreferences.network.networkstatus': 'Status mreÅ¾e',
  'stb.settings.systempreferences.network.networkstatus.defaultgateway': 'podrazumevani gejtvej',
  'stb.settings.systempreferences.network.networkstatus.description': 'Pogledaj informacije o statusu mreÅ¾e',
  'stb.settings.systempreferences.network.networkstatus.ipaddresssetting': 'podeÅ¡avanje IP adrese',
  'stb.settings.systempreferences.network.networkstatus.ipadress': 'IP adresa',
  'stb.settings.systempreferences.network.networkstatus.ipv6': 'IPv6',
  'stb.settings.systempreferences.network.networkstatus.macaddress': 'Mac adresa',
  'stb.settings.systempreferences.network.networkstatus.primarydns': 'Primarni dns',
  'stb.settings.systempreferences.network.networkstatus.secondarydns': 'Sekundarni dns',
  'stb.settings.systempreferences.network.networkstatus.subnetmask': 'subnet mask',
  'stb.settings.systempreferences.network.speedtest': 'Provera brzine',
  'stb.settings.systempreferences.network.speedtest.current speed': 'Trenutna brzina',
  'stb.settings.systempreferences.network.speedtest.description': 'Pritisnite OK za merenje brzine',
  'stb.settings.systempreferences.network.speedtest.max': 'max',
  'stb.settings.systempreferences.network.speedtest.min': 'min',
  'stb.settings.systempreferences.network.speedtest.ping': 'ping',
  'stb.settings.systempreferences.network.speedtest.server': 'server',
  'stb.settings.systempreferences.quality': 'kvalitet',
  'stb.settings.systempreferences.quality.auto': 'auto',
  'stb.settings.systempreferences.quality.bps': 'bps',
  'stb.settings.systempreferences.quality.cancel': 'otkaÅ¾i',
  'stb.settings.systempreferences.quality.description': 'prilagodi kvalitet kanala',
  'stb.settings.systempreferences.software': 'softver',
  'stb.settings.systempreferences.software.application version': 'verzija aplikacije',
  'stb.settings.systempreferences.software.description': 'trenutna verzija aplikacije i model televizora',
  'stb.settings.systempreferences.software.tv model': 'model televizora',
  'tablet.guide.alltv.favorites.newlist.title': 'Ime nove liste'
}
