/* eslint-disable quotes */

export default {
  "2": [
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-11T23:00:00.245+0000",
      "endTime": "2017-03-12T00:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T00:00:00.245+0000",
      "endTime": "2017-03-12T01:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T01:00:00.245+0000",
      "endTime": "2017-03-12T02:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T02:00:00.245+0000",
      "endTime": "2017-03-12T03:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T03:00:00.245+0000",
      "endTime": "2017-03-12T04:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T04:00:00.245+0000",
      "endTime": "2017-03-12T05:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T05:00:00.245+0000",
      "endTime": "2017-03-12T06:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T06:00:00.245+0000",
      "endTime": "2017-03-12T07:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T07:00:00.245+0000",
      "endTime": "2017-03-12T08:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T08:00:00.245+0000",
      "endTime": "2017-03-12T09:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T09:00:00.245+0000",
      "endTime": "2017-03-12T10:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T10:00:00.245+0000",
      "endTime": "2017-03-12T11:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T11:00:00.245+0000",
      "endTime": "2017-03-12T12:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T12:00:00.245+0000",
      "endTime": "2017-03-12T13:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T13:00:00.245+0000",
      "endTime": "2017-03-12T14:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T14:00:00.245+0000",
      "endTime": "2017-03-12T15:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T15:00:00.245+0000",
      "endTime": "2017-03-12T16:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T16:00:00.245+0000",
      "endTime": "2017-03-12T17:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T17:00:00.245+0000",
      "endTime": "2017-03-12T18:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T18:00:00.245+0000",
      "endTime": "2017-03-12T19:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T19:00:00.245+0000",
      "endTime": "2017-03-12T20:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T20:00:00.245+0000",
      "endTime": "2017-03-12T21:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T21:00:00.245+0000",
      "endTime": "2017-03-12T22:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    },
    {
      "id": 0,
      "channelId": 2,
      "title": "No information",
      "ageRating": null,
      "startTime": "2017-03-12T22:00:00.245+0000",
      "endTime": "2017-03-12T23:00:00.245+0000",
      "type": null,
      "pictures": null,
      "channelLogos": null,
      "categories": null,
      "hasReminder": false,
      "order": 0,
      "country": null,
      "language": null,
      "year": null,
      "description": null,
      "genres": null,
      "person": null
    }
  ]
}
